# Generated by Django 3.1 on 2022-06-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='ISI1a',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predict',
            name='ISI1b',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predict',
            name='ISI1c',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predict',
            name='PSG_C6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predict',
            name='abdomen_circumference',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='predict',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='predict',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='predict',
            name='hip_circumference',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='predict',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
    ]
