# Generated by Django 4.0.5 on 2022-06-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_auto_20220609_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
