# Generated by Django 4.0.5 on 2022-06-09 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_alter_predict_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predict',
            old_name='abdomen_circumference',
            new_name='BMI',
        ),
        migrations.RemoveField(
            model_name='predict',
            name='height',
        ),
        migrations.RemoveField(
            model_name='predict',
            name='hip_circumference',
        ),
        migrations.RemoveField(
            model_name='predict',
            name='weight',
        ),
    ]
