# Generated by Django 4.0.5 on 2022-06-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_rename_abdomen_circumference_predict_bmi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='BMI',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='predict',
            name='ISI1a',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predict',
            name='ISI1b',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predict',
            name='ISI1c',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predict',
            name='PSG_C6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predict',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predict',
            name='sex',
            field=models.IntegerField(default=0),
        ),
    ]
