# Generated by Django 4.0.5 on 2022-07-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0006_alter_predict_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
